CREATE TABLE "201611 November 2016 Reconciliation".hpvoc -- HART contest precinct vote-opportunity choice
(
	id					serial NOT NULL,
	Precinct_name		character varying,
	Split_name			character varying,
	Reporting_flag		character varying,
	Update_count		integer,
	Pct_Id				character varying,
	Pct_seq_nbr			integer,
	Reg_voters			integer,
	Turn_Out			real,
	Contest_Id			integer,
	Contest_seq_nbr		integer,
	Contest_title		character varying,
	Contest_party_name	character varying,
	Selectable_Options	integer,
	candidate_id		integer,
	candidate_name		character varying,
	Candidate_Type		character varying,
	cand_seq_nbr		integer,
	Party_Code			character varying,
	total_ballots		integer,
	total_votes			integer,
	total_under_votes	integer,
	total_over_votes	integer,
	absentee_ballots	integer,
	absentee_votes		integer,
	absentee_under_votes integer,
	absentee_over_votes	integer,
	early_ballots		integer,
	early_votes			integer,
	early_under_votes	integer,
	early_over_votes	integer,
	election_ballots	integer,
	election_votes		integer,
	election_under_votes integer,
	election_over_votes	integer,
	CONSTRAINT bps_pkey PRIMARY KEY (id)
);
